name: Deploying

on:
    push:
        branches:
            - main
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: executing remote ssh commands using ssh key
                id: ssh_deploy
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    script: |
                        cd node
                        cd evently-api
                        git stash
                        git stash clear
                        git pull
                        pm2 stop evently-api
                        pm2 delete evently-api
                        npm install
                        npm run build
                        pm2 start "npm run start" --name evently-api